TEMPLATE = app
TARGET = ../mudball
DEPENDPATH += . irrBullet-0.1.6/include tinyXML
INCLUDEPATH += . irrBullet-0.1.6/include tinyXML

LIBS += -lIrrlicht -lBulletSoftBody  -lBulletDynamics -lBulletCollision -lLinearMath

HEADERS += App.h \
           EElevator.h \
           EElevator2X.h \
           EGoal.h \
           Element.h \
           EMud.h \
           EPlatform.h \
           ERamp.h \
           ERampEnd.h \
           ERampFlat.h \
           ERampStart.h \
           EStart.h \
           ETube2.h \
           ETube2C.h \
           ETube2H.h \
           ETubeBig.h \
           ETubeBigCurve.h \
           ETubeH.h \
           EventReceiver.h \
           EWind.h \
           XEffects/CScreenQuad.h \
           XEffects/CShaderPre.h \
           XEffects/EffectCB.h \
           XEffects/EffectHandler.h \
           XEffects/EffectShaders.h \
           XEffects/XEffects.h \
           irrBullet-0.1.6/include/boxshape.h \
           irrBullet-0.1.6/include/bulletworld.h \
           irrBullet-0.1.6/include/bvhtrianglemeshshape.h \
           irrBullet-0.1.6/include/collisioncallbackinformation.h \
           irrBullet-0.1.6/include/collisionobject.h \
           irrBullet-0.1.6/include/collisionobjectaffector.h \
           irrBullet-0.1.6/include/collisionobjectaffectordelete.h \
           irrBullet-0.1.6/include/collisionshape.h \
           irrBullet-0.1.6/include/common.h \
           irrBullet-0.1.6/include/convexhullshape.h \
           irrBullet-0.1.6/include/gimpactmeshshape.h \
           irrBullet-0.1.6/include/irrbullet.h \
           irrBullet-0.1.6/include/irrbullet_compile_config.h \
           irrBullet-0.1.6/include/motionstate.h \
           irrBullet-0.1.6/include/physicsdebug.h \
           irrBullet-0.1.6/include/raycastvehicle.h \
           irrBullet-0.1.6/include/rigidbody.h \
           irrBullet-0.1.6/include/sphereshape.h \
           irrBullet-0.1.6/include/trianglemeshshape.h \
           irrBullet-0.1.6/source/boxshape.h \
           irrBullet-0.1.6/source/bulletworld.h \
           irrBullet-0.1.6/source/bvhtrianglemeshshape.h \
           irrBullet-0.1.6/source/collisioncallbackinformation.h \
           irrBullet-0.1.6/source/collisionobject.h \
           irrBullet-0.1.6/source/collisionobjectaffector.h \
           irrBullet-0.1.6/source/collisionobjectaffectordelete.h \
           irrBullet-0.1.6/source/collisionshape.h \
           irrBullet-0.1.6/source/common.h \
           irrBullet-0.1.6/source/convexhullshape.h \
           irrBullet-0.1.6/source/gimpactmeshshape.h \
           irrBullet-0.1.6/source/motionstate.h \
           irrBullet-0.1.6/source/physicsdebug.h \
           irrBullet-0.1.6/source/raycastvehicle.h \
           irrBullet-0.1.6/source/rigidbody.h \
           irrBullet-0.1.6/source/sphereshape.h \
           irrBullet-0.1.6/source/trianglemeshshape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/btBulletCollisionCommon.h \
           irrBullet-0.1.6/include/bheaders/Bullet/btBulletDynamicsCommon.h \
           irrBullet-0.1.6/include/bheaders/Bullet/Bullet-C-Api.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/btGpu3DGridBroadphase.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/btGpu3DGridBroadphaseSharedCode.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/btGpu3DGridBroadphaseSharedDefs.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/btGpu3DGridBroadphaseSharedTypes.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/btGpuDefines.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/btGpuUtilsSharedCode.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/btGpuUtilsSharedDefs.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/btThreadSupportInterface.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/MiniCLTaskScheduler.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/PlatformDefinitions.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/PosixThreadSupport.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/PpuAddressSpace.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SequentialThreadSupport.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuCollisionObjectWrapper.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuCollisionTaskProcess.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuContactManifoldCollisionAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuDoubleBuffer.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuFakeDma.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuGatheringCollisionDispatcher.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuLibspe2Support.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuSampleTaskProcess.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuSync.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/vectormath2bullet.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/Win32ThreadSupport.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletSoftBody/btSoftBody.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletSoftBody/btSoftBodyHelpers.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletSoftBody/btSoftBodyInternals.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletSoftBody/btSoftRigidCollisionAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletSoftBody/btSoftRigidDynamicsWorld.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletSoftBody/btSoftSoftCollisionAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletSoftBody/btSparseSDF.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btAabbUtil2.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btAlignedAllocator.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btAlignedObjectArray.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btConvexHull.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btDefaultMotionState.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btGeometryUtil.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btHashMap.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btIDebugDraw.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btList.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btMatrix3x3.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btMinMax.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btMotionState.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btPoolAllocator.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btQuadWord.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btQuaternion.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btQuickprof.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btRandom.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btScalar.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btStackAlloc.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btTransform.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btTransformUtil.h \
           irrBullet-0.1.6/include/bheaders/Bullet/LinearMath/btVector3.h \
           irrBullet-0.1.6/include/bheaders/Bullet/MiniCL/cl.h \
           irrBullet-0.1.6/include/bheaders/Bullet/MiniCL/cl_gl.h \
           irrBullet-0.1.6/include/bheaders/Bullet/MiniCL/cl_platform.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/BroadphaseCollision/btAxisSweep3.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/BroadphaseCollision/btBroadphaseInterface.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/BroadphaseCollision/btBroadphaseProxy.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/BroadphaseCollision/btDbvt.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/BroadphaseCollision/btDbvtBroadphase.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/BroadphaseCollision/btDispatcher.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/BroadphaseCollision/btMultiSapBroadphase.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/BroadphaseCollision/btOverlappingPairCache.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/BroadphaseCollision/btOverlappingPairCallback.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/BroadphaseCollision/btQuantizedBvh.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/BroadphaseCollision/btSimpleBroadphase.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btBoxBoxDetector.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btCollisionConfiguration.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btCollisionCreateFunc.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btCollisionDispatcher.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btCollisionObject.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btCollisionWorld.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btGhostObject.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btManifoldResult.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btSimulationIslandManager.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/btUnionFind.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionDispatch/SphereTriangleDetector.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btBox2dShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btBoxShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btCapsuleShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btCollisionMargin.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btCollisionShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btCompoundShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btConcaveShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btConeShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btConvex2dShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btConvexHullShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btConvexInternalShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btConvexPointCloudShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btConvexShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btCylinderShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btEmptyShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btMaterial.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btMinkowskiSumShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btMultiSphereShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btOptimizedBvh.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btShapeHull.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btSphereShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btStaticPlaneShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btStridingMeshInterface.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btTetrahedronShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btTriangleBuffer.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btTriangleCallback.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btTriangleMesh.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btTriangleMeshShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btTriangleShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/CollisionShapes/btUniformScalingShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/btBoxCollision.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/btClipPolygon.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/btContactProcessing.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/btGenericPoolAllocator.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/btGeometryOperations.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/btGImpactBvh.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/btGImpactMassUtil.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/btGImpactQuantizedBvh.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/btGImpactShape.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/btQuantization.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/btTriangleShapeEx.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/gim_array.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/gim_basic_geometry_operations.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/gim_bitset.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/gim_box_collision.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/gim_box_set.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/gim_clip_polygon.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/gim_contact.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/gim_geom_types.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/gim_geometry.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/gim_hash_table.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/gim_linear_math.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/gim_math.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/gim_memory.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/gim_radixsort.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/Gimpact/gim_tri_collision.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/NarrowPhaseCollision/btConvexCast.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/NarrowPhaseCollision/btConvexPenetrationDepthSolver.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/NarrowPhaseCollision/btDiscreteCollisionDetectorInterface.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/NarrowPhaseCollision/btGjkEpa2.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/NarrowPhaseCollision/btManifoldPoint.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/NarrowPhaseCollision/btPersistentManifold.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/NarrowPhaseCollision/btPointCollector.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/NarrowPhaseCollision/btRaycastCallback.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/NarrowPhaseCollision/btSimplexSolverInterface.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/Character/btCharacterControllerInterface.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/Character/btKinematicCharacterController.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btConeTwistConstraint.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btConstraintSolver.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btContactConstraint.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btContactSolverInfo.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btHinge2Constraint.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btHingeConstraint.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btJacobianEntry.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btSliderConstraint.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btSolverBody.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btSolverConstraint.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btTypedConstraint.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/ConstraintSolver/btUniversalConstraint.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/Dynamics/btActionInterface.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/Dynamics/btContinuousDynamicsWorld.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/Dynamics/btDynamicsWorld.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/Dynamics/btRigidBody.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/Dynamics/btSimpleDynamicsWorld.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/Vehicle/btRaycastVehicle.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/Vehicle/btVehicleRaycaster.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletDynamics/Vehicle/btWheelInfo.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/MiniCLTask/MiniCLTask.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/Box.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/boxBoxDistance.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuCollisionShapes.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuContactResult.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuConvexPenetrationDepthSolver.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuGatheringCollisionTask.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuLocalSupport.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuMinkowskiPenetrationDepthSolver.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuPreferredPenetrationDirections.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/SpuSampleTask/SpuSampleTask.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/vectormath/scalar/cpp/mat_aos.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/vectormath/scalar/cpp/quat_aos.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/vectormath/scalar/cpp/vec_aos.h \
           irrBullet-0.1.6/include/bheaders/Bullet/BulletMultiThreaded/vectormath/scalar/cpp/vectormath_aos.h \
           tinyXML/tinystr.h \
           tinyXML/tinyxml.h

SOURCES += ../main.cpp App.cpp \
           Element.cpp \
           EElevator.cpp \
           EElevator2X.cpp \
           EGoal.cpp \
           EMud.cpp \
           EPlatform.cpp \
           ERamp.cpp \
           ERampEnd.cpp \
           ERampFlat.cpp \
           ERampStart.cpp \
           EStart.cpp \
           ETube2.cpp \
           ETube2C.cpp \
           ETube2H.cpp \
           ETubeBig.cpp \
           ETubeBigCurve.cpp \
           ETubeH.cpp \
           EWind.cpp \
           XEffects/CShaderPre.cpp \
           XEffects/EffectHandler.cpp \
           irrBullet-0.1.6/source/boxshape.cpp \
           irrBullet-0.1.6/source/bulletworld.cpp \
           irrBullet-0.1.6/source/bvhtrianglemeshshape.cpp \
           irrBullet-0.1.6/source/collisioncallbackinformation.cpp \
           irrBullet-0.1.6/source/collisionobject.cpp \
           irrBullet-0.1.6/source/collisionobjectaffector.cpp \
           irrBullet-0.1.6/source/collisionobjectaffectordelete.cpp \
           irrBullet-0.1.6/source/collisionshape.cpp \
           irrBullet-0.1.6/source/common.cpp \
           irrBullet-0.1.6/source/convexhullshape.cpp \
           irrBullet-0.1.6/source/gimpactmeshshape.cpp \
           irrBullet-0.1.6/source/motionstate.cpp \
           irrBullet-0.1.6/source/physicsdebug.cpp \
           irrBullet-0.1.6/source/raycastvehicle.cpp \
           irrBullet-0.1.6/source/rigidbody.cpp \
           irrBullet-0.1.6/source/sphereshape.cpp \
           irrBullet-0.1.6/source/trianglemeshshape.cpp \
           tinyXML/tinystr.cpp \
           tinyXML/tinyxml.cpp \
           tinyXML/tinyxmlerror.cpp \
           tinyXML/tinyxmlparser.cpp


OBJECTS_DIR = .build/obj
MOC_DIR     = .build/moc
RCC_DIR     = .build/rcc
UI_DIR      = .build/ui

